name: Deploy

on:
  workflow_dispatch:


jobs:
  Deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set Docker image tag using GitHub run number
      run: echo "IMAGE_TAG=${{ github.run_number }}" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build . -t sumit6081/next-js-app:${{ env.IMAGE_TAG }}

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push sumit6081/next-js-app:${{ env.IMAGE_TAG }}
